version: '3.8'

services:
    api:
        build:
            context: ./cmd/api/
            dockerfile: Dockerfile
        container_name: todo_api
        ports:
            - '8080:8080'
        depends_on:
            - postgres
            - redis
            - kafka
    dbservice:
        build:
            context: ./cmd/dbservice/
            dockerfile: Dockerfile
        container_name: todo_dbservice
        ports:
            - '50051:50051'
        depends_on:
            - postgres
            - redis
            - kafka
    postgres:
        image: postgres:17-alpine
        container_name: todo_postgres
        ports:
            - '5432:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=todo_db
            - POSTGRES_SSLMODE=disable
        restart: unless-stopped
    redis:
        image: redis:7-alpine
        container_name: todo_redis
        ports:
            - '6379:6379'
        volumes:
            - ./redis_data:/data
        environment:
            - REDIS_PASSWORD=redis_password
        restart: unless-stopped
        command: redis-server --appendonly yes
    kafka:
        image: confluentinc/cp-kafka:7.4.0
        container_name: todo_kafka
        ports:
            - '9092:9092'
        environment:
            - KAFKA_NODE_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
            - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
            - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
        volumes:
            - ./kafka-data:/tmp/kraft-combined-logs

volumes:
    redis_data:
    kafka_data:
    postgres_data:

networks:
    default:
        driver: bridge
