api_service:
    http:
        host: 'localhost'
        port: '8080'
        timeout: '10s'
    grpc_db_service:
        host: 'localhost'
        port: '50051'
        timeout: '10s'
    kafka:
        brokers:
            - 'localhost:9092'
        topic: 'todo_topic'

db_service:
    grpc:
        host: '0.0.0.0'
        port: '50051'
        timeout: '10s'
    postgres:
        host: 'localhost'
        port: '5432'
        user: 'postgres'
        password: 'postgres'
        dbname: 'todo_db'
        sslmode: 'disable'
    redis:
        host: 'localhost'
        port: '6379'
        db: 0
        password: ''
        timeout: '5s'
