api_service:
    http:
        port: '8081'
        timeout: '10s'
    grpc_db_service:
        target: 'localhost:50051'
        timeout: '10s'
    kafka:
        brokers:
            - 'localhost:9094'
        topic: 'events'
    logger:
        level: 'debug'

db_service:
    grpc:
        target: '0.0.0.0:50051'
        timeout: '10s'
    postgres:
        host: 'localhost'
        port: '5432'
        user: 'postgres'
        password: 'postgres'
        dbname: 'todo_db'
        sslmode: 'disable'
        max_connections: 50 # Максимум соединений в пуле
        max_idle_time: '5m'
    redis:
        host: 'localhost'
        port: '6379'
        db: 0
        password: ''
        timeout: '5s'
        cache_ttl: '4m'
    logger:
        level: 'info'
